/// Flutter icons GitIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GitIcons
///      fonts:
///       - asset: fonts/GitIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class GitIcons {
  GitIcons._();

  static const _kFontFam = 'GitIcons';
  static const _kFontPkg = null;

  static const IconData github_circled = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf113, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gittip = IconData(0xf184, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_squared = IconData(0xf1d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git = IconData(0xf1d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gitlab = IconData(0xf296, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_squared = IconData(0xf300, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData towel = IconData(0xf200, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
